class Category {
  final String id;
  final String name;
  final String imagePath; //replaces original emoji with where images are stored

  final List<String> words;
  // Constructor just like java

  const Category({
    required this.id,
    required this.name,
    required this.imagePath,
    required this.words,
  });
}

final List<Category> builtInCategories = [
  Category(
    id: 'classes',
    name: 'Classes',
    imagePath: 'assets/categories/BCA_classes.png',
    words: [
      'Calc/Math',
      'English',
      'AP Comp Sci',
      'Chem',
      'Physics',
      'Online Health',
      'Gym/PE',
      'Spanish',
      'Mandarin',
      'French',
      'History',
      //add more classes here
    ],
  ),
  Category(
    id: 'teachers',
    name: 'Teachers',
    imagePath: 'assets/categories/BCA_teachers.png',
    words: [
      'Dr. Reeves',
      'Ms. Sorrentino',
      'Mr. Liva',
      'Mr. Lang',
      'Ms. Wallace',
      'Mr. Dr. Crane',
      'Mr. Kalata',
      'Ms. Leonardi',
      'Mr. Russo',
      'Dr. Dogru',
      'Ms. Sawhney',
      'Mr. Gutierrez',
      'Dr. Pinto',
      'Mr. Kaplan',
      'Ms. Feuss',
      'Mr. Dobrich',
      'Ms. Fillebrown',
      'Mr. Zhang',
      'Mr. Spinelli',
      'Mr. Alschen',
      'Ms. Dr. Crane',
      'Ms. Villanova',
      'Mr. Kramer',
      'Ms. Blake',
      'Ms. Pagano',
      'Ms. Kim',
      'Mr. Madden',
      'Mr. Samarakone',
      'Mr. Davis',
      'Mr. Respass',
      'Ms. Crimmel',
      'Mr. Guthrie',
      'Mr. Nodarse',
      'Ms. Andaloro',
      'Mr. Kaser',
      'Dr. Abramson',
      'Ms. Seltzer',
      'Dr. Penev',
      'Ms. Heitzman',
      'Mr. Walsh',
      'Mr. Djedji',
      'Ms. Casarico',
      'Ms. Zangara',
      'Dr. Zubov',
      'Mr. Marmora',
      'Mr. Torres',
      'Ms. Calandra',
      'Ms. James',
      'Dr. Waldron',
      'Mr. Pinyan',
      'Ms. Ogden',
      'Ms. Ponce',
      'Mr. Isecke',
      'Mr. Symons',
      'Mr. Bonanomi',
      'Ms. Pero',
      'Ms. Fuentes',
      'Dr. Kim',
      'Mr. Lemma',
      'Ms. Halligan',
      'Ms. Janssen',
      'Mr. Lancaster',
      'Ms. Kaba',
      'Ms. Sousa',
      //we will have to add more teachers here lol
    ],
  ),
  Category(
    id: 'students',
    name: 'Students',
    imagePath: 'assets/categories/BCA_students.png',
    words: [
      'Ian Pena',
      'Nikhil Maalige',
      'Michael Polyakov',
      'Ari Wachtel',
      'Olivia Smith',
      'Kai Lindemer',
      'Liel Manalac',
      'Jacob Korn',
      'Julian Zhu',
      'Ryan Benkovich',
      'Pinak Unawane',
      'Gianna Park',
      'Amir Jeffries-El',
      'Enric Soni',
      'Justin Na',
      'Elijah Park',
      'Alexander Marynchev',
      'Joaquin Ealdama',
      'Yash Korgaonkar',
      'Justin Canuela',
      'Erik Turdiu',
      'Eunseo Whaong',
      'Aaryan Manrao',
      'Gabriel Mojica',
      'Alexander Sanfiz',
      'Giada Jimenez',
      'Ryan Arumemi',
      'Vivaan Joshi',
      'Maximus Neri',
      'Kunj Parikh',
      'Bozhan Shang',
      'Christian Fabian',
      'Avneet Kaur',
      'Yashvi Trivedi',
      'Sanya Shekhar',
      'Hanvit Lee',
      'Azlan Khan',
      'Jonah Kim',
      'Raameen Farhan',
      'Branden Kim',
      'Alyssa Kim',
      'Barbara Leschinsky',
      'Paavni Yadav',
      'Nicole Arno',
      'Brielle Han',
      'Cheryn Cho',
      'Lara Arslan',
      'Olivia Mendelsohn',
      'Amie Jin',
      'Sophie Kakuda',
      'Evangeline Lee',
      'Evan Moy',
      'Alexandra Goldovskiy',
      'Reyansh Jaggi',
      'Priscila Alcala',
      'Jiye Lee',
      'Gabriela Iwuc',
      'Emmanuel Cohn',
      'Hyunseo Ryu',
      'Bella Velasquez',
      'Polly Yakubovich',
      'Luna Cannone',
      'Amalia Ponomarev',
      'Nathan Averboukh',
      'Brian Gao',
      'Isabella Cintron',
      'Erin Son',
      'Hawon Song',
      'Alessandra Sommar',
      'Nicholas Lee',
      'Haeun Jung',
      'Claire Kim',
      'Cara Ko',
      'Gianna Kim',
      'Rania Rangrez',
      'Morgan Pallante',
      'Owen Tzeng',
      'Jiayi Xu',
      'Shelby York',
      'Willow Yoo',
      'Nora Cullen',
      'Landon Donskoy',
      'Isabella Irizarry Garcia',
      'Emily Biesiadecki',
      'Abigail Karpova',
      'Hannah Lee',
      'Eunice Cho',
      'Gina Gil',
      'Alyson Lee',
      'Lukas Kwon',
      'Sorin Choi',
      'Aryn Ryu',
      'Daniella Berezin',
      'Jillian Gunderman',
      'Aisha Shafoat',
      'Nikhil Diwan',
      'Nathaniel Ng',
      'Jeremiah Markose',
      'Gurvinder Ghotra',
      'Ryan Yamani',
      'Omar Saad',
      'Michael Pylypovych',
      'Yashvi Rateshwar',
      'Vikram Gangu',
      'Isabella Baratta',
      'Lauren Cho',
      'Alex Moell',
      'Ekin Bozer',
      'Skanda Ramanathan',
      'Vedanti Rawal',
      'Joshua Kim',
      'Zachary Friedman',
      'Joshua Lee',
      'Emily Gong',
      'Eshan Bakshi',
      'Quincy Ibeabuchi',
      'Jane Elliott',
      'Golan Yoskowitz',
      'Emmeline Chu',
      'Evelyn Lehmann',
      'Alyssa Nasr',
      'Ewan Kim',
      'Srivathsav Vadlamudi',
      'Michael Bassily',
      'Danny Paik',
      'August Rechner',
      'George Elgendi',
      'Jaehyun Hwang',
      'Lina Simonyan',
      'Aakrithi Ram',
      'Santiago Franco De La Matta',
      'Kaho Ishihara',
      'Ivan Santana',
      'Taeyun Patel-Pak',
      'Soham Kaushal',
      'Yoonseo Jang',
      'Claire Shi',
      'Sevita Palaniappan',
      'Isaac Kim',
      'Andrew Hong',
      'Lillian Day',
      'Bryan Xiao',
      'Katie Chung',
      'Rohi Hubert',
      'Janelle Morales',
      'Daniel Degnan',
      'Julianna Marton',
      'Gevan Ha',
      'Salvatore Calafiore',
      'Joseph Park',
      'Gavin Vadnais',
      'Alex Andersen',
      'Demir Akar',
      'Joshua Neri',
      'Freja Jepsen',
      'Hitanshee Sheth',
      'Aryan Dhingra',
      'Yuditt Mehta',
      'Rishi Talavia',
      'Aalok Pathak',
      'Lucas Malachovsky',
      'Alexander Li',
      'Esther Jung',
      'Enea Ferati',
      'Aiden Lee',
      'Thomas Tynan',
      'Natalia Karcz',
      'Yuval Alon',
      'Jocelyn Ng',
      'Aarya Pathak',
      'Elshod Pirimkulov',
      'Gabrielle Barlan',
      'Ansh Patel',
      'Nathaniel Schmude',
      'Allison Guallpa',
      'Varsha Tyagi',
      'Ipek Oruc',
      'Alyssa Lee',
      'Ryan Ramos',
      'Gaelle Ngabo',
      'Vaishnavi Mudumbi',
      'Danielle Abad',
      'Nazanin Mansouri',
      'Aasiba Mohamed Dhakir Hussain',
      'Nicole Botros',
      'Emily Amoss',
      'Hyejin An',
      'Esther Yoo',
      'Sana Kashyap',
      'Khawlah Alsaleem',
      'Wyatt Remegio',
      'Basma Mohamed',
      'Aliyah Shams',
      'Adeline Alipui',
      'Mannat Minhas',
      'Anna Bella Cappola',
      'Oliver Siringan',
      'Daniel Yang',
      'Hyuna Kang',
      'Ava Huie-Pasigan',
      'Dea Cela',
      'Christian Bakunas',
      'Leo Toake',
      'Bethany Zheng',
      'Michelle Kossakowska-Dominguez',
      'Singhe Lenjor',
      'Reece Sit',
      'Avya Patel',
      'Afreen Akhtar',
      'Julia Magda',
      'Olivia Kim',
      'Johana Zhu',
      'Anthony Antonov',
      'Takumi Marescot',
      'Rachel Lee',
      'Joann Park',
      'Amy Miyata',
      'Katherine Zwernemann',
      'Kayden Oh',
      'Jayita Iyengar',
      'Ashley Park',
      'Neel Gudapati',
      'Srivarenya Vempati',
      'Jairus Pena',
      'Shaya Tabar',
      'Bella Pandey',
      'Delancey Van Meir',
      'Leah Nguyen',
      'Yaseen Saeed',
      'Ritvik Sethi',
      'Maayan Ram',
      'Guy Goren',
      'Samhita Tumuluri',
      'Agatha Shaikhutdinova',
      'Clara Sullivan',
      'Yuri Lee',
      'Lanamaria Mehetarian',
      'David Park',
      'Sydney Devries',
      'Jason Goodman',
      'Nathaniel Avena',
      'Aiden Lee',
      'Kana Watanabe',
      'Amrita Kumar',
      'Yebin Lee',
      'Amelia Blume',
      'Aidan Kim',
      'Anshika Patibandla',
      'Ashna Patel',
      'Alya Bizel',
      'Isabella Hong',
      'Samuel Kim',
      'Naisha Goel',
      'Matthew Cornelius',
      'Nandita Dani',
      'Tanisi Mohanty',
      'Nainika Mandayam',
      'Elad Shav',
      'Alp Turkgeldi',
      'Grace Zhou',
      'Cristiano Santiago',
      'Patricia Mosticchio',
      'Avi Patel',
      'Alanna Onyango',
      'Renee Lee',
      'Emily Say',
      'Evva Vassiliou',
      'Calvin Jang',
      'Max Deninzon',
      'Solomon Pak',
      'Emily Tong',
      'Mia Bharam',
      'David Prokopyev',
      'Brooklyn Pak',
    ],
  ),
  // More categories can be added, as well as more values in each category in the future
];

// custom decks the user makes while the app is running
// this does not save forever yet, but it works for level 2
final List<Category> customCategories = [];
